[blockstop_scan]
index = default
sourcetype = blockstop:scan
source = blockstop
interval = 300
disabled = 0

# HTTP Event Collector (HEC) configuration
[http://blockstop_hec]
disabled = 0
source = blockstop_api
sourcetype = blockstop:ingest
index = main
output_group = default
event_type = scan
